/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.anas.accounting.gui;

/**
 *
 * @author Muhammad Anas
 */
public class MainWindow extends javax.swing.JFrame
{

    /**
     * Creates new form MainWindow
     */
    public MainWindow()
    {
        initComponents();
        dashBoard.setParentWindow( this );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centralPanel = new javax.swing.JPanel();
        dashBoard = new pk.anas.accounting.gui.DashBoard();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AccountingSoftware");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        centralPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        centralPanel.add(dashBoard, gridBagConstraints);

        getContentPane().add(centralPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Customers");

        jMenuItem2.setText("Add New Customer");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Suppliers");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Add New Supplier");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Products");

        jMenuItem4.setText("Add New Product");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Orders");

        jMenu9.setText("Sales Orders");

        jMenuItem5.setText("New Sales Order");
        jMenu9.add(jMenuItem5);

        jMenu3.add(jMenu9);

        jMenu10.setText("Purchase Orders");

        jMenuItem6.setText("New Purchase Order");
        jMenu10.add(jMenuItem6);

        jMenu3.add(jMenu10);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Accounts");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Transactions");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Reports");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Help");

        jMenuItem1.setText("About");
        jMenu8.add(jMenuItem1);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ////////////////// -- Our Custom Methods -- \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    //////////////////////////////////////////////////////////////////////////
    public void openCustomersManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openSuppliersManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openSalesOrdersManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openPurchaseOrdersManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openProductsManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openProductsCategoriesManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openBankAccountsManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openCapitalAccountsManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openBankTransactionsManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openCapitalTransactionsManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openCashTransactionsManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    
    public void openReportsManager()
    {
        centralPanel.removeAll();
        centralPanel.repaint();
        this.revalidate();
    }
    //////////////////////////////////////////////////////////////////////////
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenu2ActionPerformed
    {//GEN-HEADEREND:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centralPanel;
    private pk.anas.accounting.gui.DashBoard dashBoard;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
